@startuml
class Campaign {
    + Clone() : Campaign
    + Copy(campaign:Campaign) : void
}
Campaign --> "Id" Guid
Campaign --> "ImageBanner" String
Campaign --> "Showcase" Showcase
Campaign --> "StartDate" DateTime
Campaign --> "EndDate" DateTime
@enduml
