@startuml
class ProductRepository {
    + ProductRepository(context:EfContext)
    + <<override>> Update(obj:Product) : void
}
class "Repository`1"<T> {
}
"Repository`1" "<Product>" <|-- ProductRepository
@enduml
