@startuml
class EfContextFactory {
    + CreateDbContext(args:string[]) : EfContext
}
class "IDesignTimeDbContextFactory`1"<T> {
}
"IDesignTimeDbContextFactory`1" "<EfContext>" <|-- EfContextFactory
@enduml
