@startuml
!include .\\Application.Sales\Program.puml
!include .\\Application.Sales\Startup.puml
!include .\\Applications.Stock\Program.puml
!include .\\Applications.Stock\Startup.puml
!include .\\Application.Sales\Controllers\CampaignController.puml
!include .\\Application.Sales\Controllers\OrderController.puml
!include .\\Application.Sales\Controllers\ReservationController.puml
!include .\\Application.Sales\Controllers\ShowcaseController.puml
!include .\\Application.Sales\Controllers\TesteController.puml
!include .\\Applications.Stock\Controllers\BranchOfficeController.puml
!include .\\Applications.Stock\Controllers\InvoiceController.puml
!include .\\Applications.Stock\Controllers\LocationController.puml
!include .\\Applications.Stock\Controllers\ProductController.puml
!include .\\Applications.Stock\Controllers\ProductManagementController.puml
!include .\\Applications.Stock\Controllers\ProductTransitionController.puml
!include .\\Applications.Stock\Controllers\ProviderController.puml
!include .\\Applications.Stock\Controllers\TesteController.puml
!include .\\Applications.Stock\Controllers\WarehouseController.puml
!include .\\Domain.Comuns\Interfaces\IRepository.puml
!include .\\Domain.Payments\Enumerators\Status.puml
!include .\\Domain.Payments\Models\Campaign.puml
!include .\\Domain.Payments\Models\Order.puml
!include .\\Domain.Payments\Models\OrdersShowCases.puml
!include .\\Domain.Payments\Models\Reservation.puml
!include .\\Domain.Payments\Models\Showcase.puml
!include .\\Domain.Stock\Enumerators\InvoiceType.puml
!include .\\Domain.Stock\Enumerators\TransitionType.puml
!include .\\Domain.Stock\Interfaces\IHandlerInvoice.puml
!include .\\Domain.Stock\Interfaces\IInvoice.puml
!include .\\Domain.Stock\Models\BranchOffice.puml
!include .\\Domain.Stock\Models\Invoice.puml
!include .\\Domain.Stock\Models\Location.puml
!include .\\Domain.Stock\Models\Payment.puml
!include .\\Domain.Stock\Models\Product.puml
!include .\\Domain.Stock\Models\ProductManagement.puml
!include .\\Domain.Stock\Models\ProductProvider.puml
!include .\\Domain.Stock\Models\ProductTransition.puml
!include .\\Domain.Stock\Models\Provider.puml
!include .\\Domain.Stock\Models\Warehouse.puml
!include .\\Infrastructure.Comuns\Context\EfContext.puml
!include .\\Infrastructure.Comuns\Context\EfContextFactory.puml
!include .\\Infrastructure.Comuns\Migrations\20201114202931_Init.puml
!include .\\Infrastructure.Comuns\Migrations\20201114202931_Init.Designer.puml
!include .\\Infrastructure.Comuns\Migrations\20201114220410_AddReservations.puml
!include .\\Infrastructure.Comuns\Migrations\20201114220410_AddReservations.Designer.puml
!include .\\Infrastructure.Comuns\Migrations\EfContextModelSnapshot.puml
!include .\\Infrastructure.Comuns\Repositories\Repository.puml
!include .\\Infrastructure.Sales\Repositories\CampaignRepository.puml
!include .\\Infrastructure.Sales\Repositories\OrderRepository.puml
!include .\\Infrastructure.Sales\Repositories\OrdersShowcasesRepository.puml
!include .\\Infrastructure.Sales\Repositories\ReservationRepository.puml
!include .\\Infrastructure.Sales\Repositories\ShowcaseRepository.puml
!include .\\Infrastructure.Stock\Repositories\BranchOfficeRepository.puml
!include .\\Infrastructure.Stock\Repositories\InvoiceRepository.puml
!include .\\Infrastructure.Stock\Repositories\LocationRepository.puml
!include .\\Infrastructure.Stock\Repositories\ProductManagementRepository.puml
!include .\\Infrastructure.Stock\Repositories\ProductProviderRepository.puml
!include .\\Infrastructure.Stock\Repositories\ProductRepository.puml
!include .\\Infrastructure.Stock\Repositories\ProductTransitionRepository.puml
!include .\\Infrastructure.Stock\Repositories\ProviderRepository.puml
!include .\\Infrastructure.Stock\Repositories\WareHouseRepository.puml
!include .\\Utils\Helpers\ChainInputInvoice.puml
!include .\\Utils\Helpers\ChainInternalOutputInvoice.puml
!include .\\Utils\Helpers\ChainLossOutputInvoice.puml
!include .\\Utils\Helpers\ChainOutOfStockInvoice.puml
!include .\\Utils\Helpers\ChainOutputInvoice.puml
!include .\\Utils\Helpers\ChainReturnOutputInvoice.puml
!include .\\Utils\Helpers\HandlerInvoiceBase.puml
!include .\\XUnitTests\Controllers\InvoiceControllerTests .puml
!include .\\XUnitTests\Controllers\LocationControllerTests .puml
!include .\\XUnitTests\Controllers\ProductControllerTests.puml
!include .\\XUnitTests\Controllers\ProductManagementControllerTests .puml
!include .\\XUnitTests\Controllers\ProductTranstionControllerTests.puml
!include .\\XUnitTests\Controllers\ProviderControllerTests.puml
!include .\\XUnitTests\Controllers\WarehouseControllerTests.puml
!include .\\XUnitTests\Mock\InvoiceMockRepository.puml
!include .\\XUnitTests\Mock\LocationMockRepository.puml
!include .\\XUnitTests\Mock\MockRepository.puml
!include .\\XUnitTests\Mock\ProductManagementMockRepository.puml
!include .\\XUnitTests\Mock\ProductMockRepository.puml
!include .\\XUnitTests\Mock\ProductTransitionMockRepository.puml
!include .\\XUnitTests\Mock\ProviderMockRepository.puml
!include .\\XUnitTests\Mock\WarehouseMockRepository.puml
!include .\\Application.Sales\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Application.Sales\obj\Debug\netcoreapp3.1\Application.Sales.AssemblyInfo.puml
!include .\\Application.Sales\obj\Debug\netcoreapp3.1\Application.Sales.MvcApplicationPartsAssemblyInfo.puml
!include .\\Applications.Stock\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Applications.Stock\obj\Debug\netcoreapp3.1\Application.Stock.AssemblyInfo.puml
!include .\\Applications.Stock\obj\Debug\netcoreapp3.1\Application.Stock.MvcApplicationPartsAssemblyInfo.puml
!include .\\Domain.Comuns\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Domain.Comuns\obj\Debug\netcoreapp3.1\Domain.Comuns.AssemblyInfo.puml
!include .\\Domain.Payments\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Domain.Payments\obj\Debug\netcoreapp3.1\Domain.Sales.AssemblyInfo.puml
!include .\\Domain.Stock\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Domain.Stock\obj\Debug\netcoreapp3.1\Domain.Stock.AssemblyInfo.puml
!include .\\Infrastructure.Comuns\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Infrastructure.Comuns\obj\Debug\netcoreapp3.1\Infrastructure.Comuns.AssemblyInfo.puml
!include .\\Infrastructure.Sales\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Infrastructure.Sales\obj\Debug\netcoreapp3.1\Infrastructure.Sales.AssemblyInfo.puml
!include .\\Infrastructure.Stock\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Infrastructure.Stock\obj\Debug\netcoreapp3.1\Infrastructure.Stock.AssemblyInfo.puml
!include .\\Utils\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Utils\obj\Debug\netcoreapp3.1\Util.AssemblyInfo.puml
!include .\\XUnitTests\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\XUnitTests\obj\Debug\netcoreapp3.1\XUnitTests.AssemblyInfo.puml
@enduml
